[package]
name = "kael-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
async-channel.workspace = true
portable-pty.workspace = true

tokio.workspace = true
